#!/usr/bin/env bash

# Take all the individual tests and roll them into one test suite 

allTests="generated-tests.bats"

echo '#!/usr/bin/env bats' > ${allTests}
echo 'source ${PROVISIO_ROOT}/libexec/provisio-functions.bash' >> ${allTests}
echo >> ${allTests}

for testFile in $(find ${PROVISIO_ROOT}/tools -name test.bats)
do
  sed -e 's/^#.*$//' -e 's/^source.*$//' -e '/^$/d' ${testFile} >> ${allTests}
  echo >> ${allTests}
done

bats ${allTests}
