---
id: krew
name: Krew
defaultVersion: 0.4.1
layout: file
executable: krew
packaging: TARGZ
osMappings:
  Darwin: darwin
  Linux: linux
archMappings:
  x86_64: amd64
urlTemplate: https://github.com/kubernetes-sigs/krew/releases/download/v{version}/krew.tar.gz
# Now this tarball contains the versions for all systems (sigh)
tarSingleFileToExtract: ./krew-{os}_{arch}
