#!/usr/bin/env bash
set -e
[ -n "$PROVISIO_DEBUG" ] && set -x

# ------------------------------------------------------------------------------
# A little script to generate a profile yaml from the existing tool descriptors.
# Once you run it you can edit as you wish. Produces a file that looks something
# like this:
#
# tools:
#  terraform:
#    version: 0.12.21
#  octant:
#    version: 0.10.2
#  minikube:
#    version: 1.7.3
# ------------------------------------------------------------------------------

PROFILE_NAME="$1"
[ -z "${PROFILE_NAME}" ] && echo && echo "You must provide a profile name!" && echo && exit
PROFILE="${PROFILE_NAME}.yaml"

source ${PROVISIO_ROOT}/config/provisio-functions.bash

echo "tools:" >> ${PROFILE}
for d in `find ${PROVISIO_ROOT}/config/tools -name descriptor.yml`
do
  eval $(parse_yaml_with_lists $d)
  echo "  ${id}:" >> ${PROFILE}
  echo "    version: ${defaultVersion}" >> ${PROFILE}
done
