#!/usr/bin/env bash
# ------------------------------------------------------------------------------
# This was taken completely from jenv
# ------------------------------------------------------------------------------

set -e
[ -n "$PROVISIO_DEBUG" ] && set -x

resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

resolvepath() {
  local cwd="$(pwd)"
  cd $1
  echo "$(pwd)"
  cd "$cwd"
}

samedir()  {
  if [ -d $1 ] && [ -d $2 ]; then
  local path1="$(resolvepath $1)"
  local path2="$(resolvepath $2)"

  if [ $path1 == $path2 ]; then
   return 0;
  else
   return 1;
  fi
fi
return 0;
}

if [ -z "${PROVISIO_ROOT}" ]; then
  PROVISIO_ROOT="${HOME}/.provisio"
else
  PROVISIO_ROOT="${PROVISIO_ROOT%/}"
fi
export PROVISIO_ROOT

if [ -z "${PROVISIO_DIR}" ]; then
  PROVISIO_DIR="$(pwd)"
else
  cd "$PROVISIO_DIR" 2>/dev/null || {
    echo "provisio: cannot change working directory to \`$PROVISIO_DIR'"
    exit 1
  } >&2
  PROVISIO_DIR="$(pwd)"
  cd "$OLDPWD"
fi
export PROVISIO_DIR

shopt -s nullglob

bin_path="$(abs_dirname "$0")"

if ! samedir "${PROVISIO_ROOT}" "$bin_path/../"  ; then
   PROVISIO_INSTALL_DIR=$(resolvepath "$bin_path/../")
else
    PROVISIO_INSTALL_DIR=$PROVISIO_ROOT
fi
   export PROVISIO_INSTALL_DIR

for plugin_bin in "${PROVISIO_ROOT}/plugins/"*/bin; do
  bin_path="${bin_path}:${plugin_bin}"
done

export PATH="${bin_path}:${PATH}"

hook_path="${PROVISIO_HOOK_PATH}"
for plugin_hook in "${PROVISIO_ROOT}/plugins/"*/etc/provisio.d; do
  hook_path="${hook_path}:${plugin_hook}"
done

export PROVISIO_HOOK_PATH=$hook_path

shopt -u nullglob

command="$1"
case "$command" in
"" | "-h" | "--help" )
  echo -e "$(provisio --version)\n$(provisio-help)" >&2
  ;;
* )
  command_path="$(command -v "provisio-$command" || true)"
  if [ -z "$command_path" ]; then
    echo "provisio: no such command \`$command'" >&2
    exit 1
  fi

  shift 1
  exec "$command_path" "$@"
  ;;
esac
