---
id: yq
name: yq
defaultVersion: 4.9.6
layout: file
executable: yq
packaging: TARGZ
osMappings:
  Darwin: darwin
  Linux: linux
archMappings:
  x86_64: amd64
# https://github.com/mikefarah/yq/releases/download/v4.9.8/yq_linux_amd64.tar.gz
# https://github.com/mikefarah/yq/releases/download/v4.9.8/yq_darwin_amd64.tar.gz
urlTemplate: https://github.com/mikefarah/yq/releases/download/v{version}/yq_{os}_{arch}.tar.gz
tarSingleFileToExtract: ./yq_{os}_{arch}
