---
id: kind
name: Kind
defaultVersion: 0.11.1
layout: file
executable: kind
packaging: FILE
osMappings:
  Darwin: darwin
  Linux: linux
archMappings:
  x86_64: amd64
# https://github.com/kubernetes-sigs/kind/releases/download/v0.11.1/kind-darwin-amd64
# https://github.com/kubernetes-sigs/kind/releases/download/v0.11.1/kind-linux-amd64
urlTemplate: https://github.com/kubernetes-sigs/kind/releases/download/v{version}/kind-{os}-{arch}
