---
id: kubectl
name: KubeCtl
defaultVersion: 1.21.0
layout: file
executable: kubectl
packaging: FILE
osMappings:
  Darwin: darwin
  Linux: linux
archMappings:
  x86_64: amd64
# https://dl.k8s.io/release/v1.21.0/bin/linux/amd64/kubectl
# https://dl.k8s.io/release/v1.21.0/bin/darwin/amd64/kubectl
urlTemplate: https://dl.k8s.io/release/v{version}/bin/{os}/{arch}/kubectl
